### ISSUE TITLE
PostgreSQL - JPA 연동시 User 예약어 문제

### ISSUE THREAD

**Issue by dhbaek2004** [dhbaek2004/ManhattanLittleBoy#15]
User Domain에 속성과 관계들을 정상적으로 설정 했음에도 

Build시 Table이 정상적으로 생성되지 않는 이슈가 있었습니다.

이유는 User와 order 라는 단어는 PostgreSQL에서 예약어로 사용중이기 때문입니다.

아래 링크는 PostgreSQL에서 사용하는 예약어 목록 입니다.

https://www.postgresql.org/docs/13/sql-keywords-appendix.html

**Comment by drather** [comment]
User Domain에 속성과 관계들을 정상적으로 설정 했음에도

Build시 Table이 정상적으로 생성되지 않는 이슈가 있었습니다.

이유는 User와 order 라는 단어는 PostgreSQL에서 예약어로 사용중이기 때문입니다.

아래 링크는 PostgreSQL에서 사용하는 예약어 목록 입니다.

https://www.postgresql.org/docs/13/sql-keywords-appendix.html
